security:
    providers:
        auth0_users:
            id: App\Security\Auth0UserProvider

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: auth0_users
            custom_authenticators:
                - App\Security\SessionLoginAuthenticator
            entry_point: App\Security\Auth0LoginEntryPoint

    access_control:
        - { path: ^/profile$, roles: ROLE_USER }
        - { path: ^/package/.+/review$, roles: ROLE_USER }
        - { path: ^/upload/package, roles: ROLE_USER }
        - { path: ^/api/package, roles: ROLE_USER }
        - { path: ^/publish, roles: ROLE_USER }
