# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

marketplace_homepage:
    path: /
    controller: App\Controller\MarketplaceController::homepage

marketplace_index:
    path: /browse
    controller: App\Controller\MarketplaceController::index

marketplace_upload_package:
    path: /upload/package
    controller: App\Controller\MarketplaceController::uploadPackage

profile_page:
    path: /profile
    controller: App\Controller\ProfileController::index

review_submit:
    path: /package/{package}/review
    controller: App\Controller\ReviewController::submit
    methods: [POST]
    requirements:
        package: .+

marketplace_download:
    path: /package/{name}/download
    controller: App\Controller\MarketplaceController::download
    requirements:
        name: .+

marketplace_detail:
    path: /package/{package}
    controller: App\Controller\MarketplaceController::detail
    requirements:
        package: .+
